name: Custom fluentd image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/wozz/fluentd:v1.16-${{github.run_id}}
        docker push ghcr.io/wozz/fluentd:v1.16-${{github.run_id}}
    - name: Build Docker Image for arm64
      run: |
        docker buildx build --platform linux/arm64 --file Dockerfile.arm64 --push -t ghcr.io/wozz/fluentd:v1.16-arm64-${{github.run_id}} .
